keymaps/julia-client.cson
Mac-equivalent keybindings for Linux/Windows.
Have you decided on a keybinding for ``clear-inline-results``?
=> Add keybindings for linux/windows.

lib/connection/process.coffee, lib/julia-client.coffee
=> Fix "Powershell not spawned" error.

jl/boot.jl, jl/caches.jl, lib/config.coffee, lib/connection/process.coffee, lib/connection/spawnInterruptibleJulia.ps1, lib/connection/terminal.coffee
Putting together some bits so that we can dump Julia into the Atom app and have julia-client find it.
I'm also going to try and hack around the module precompilation issues so that we can bundle precompiled packages. Overall, I'm hoping that we can get the time to download Juno, install it and produce your first plot down to under a minute.
=> Support for bundled Julia

lib/runtime/evaluation.coffee
PRs for getting actual underline docs and a nice goto view are incoming
Also: I dunno whether that way of getting the current module is "good", but it works and I kinda like it. cc @one-more-minute
=> fix docs and methods for now

keymaps/julia-client.cson, lib/connection/process.coffee, lib/package/commands.coffee, lib/runtime.coffee, lib/runtime/console.coffee, lib/runtime/modules.coffee, lib/ui.coffee, lib/ui/console.coffee, package.json, styles/julia-client.less
This is really much nicer. I could really go in for this whole model/view thing.
Eyes are appreciated!
=> Module refactor + console eval

lib/misc.coffee, lib/misc/blocks.coffee, lib/misc/scopes.coffee, lib/runtime/completions.coffee, lib/runtime/evaluation.coffee, lib/ui.coffee
This is a reasonable extra chunk of code but in the long run it will save us a lot; eventually I want to get rid of the ugly parsing stuff in CodeTools.jl completely as well as the dependency on JuliaParser.jl. Doing the parsing in the frontend has its own benefits, including a more responsive feel, less data to send over the wire, and a much simplified eval cycle. Eyes welcome!
=> Implement block finding in Atom

lib/package/commands.coffee
I found myself killing the process and running execute-all alot which is quite slow. This makes it pretty fast
=> add command 'julia-client:reset-workspace'

lib/runtime/evaluation.coffee
instead of using inkIDs
ref: https://github.com/JunoLab/atom-ink/pull/39
=> switch to using atoms buffer ids

lib/misc/blocks.coffee
instead of preserving the column and staying on the first row. I realize the column-preserving probably happened for a reason, but it feels strange to me ;)
=> move to the last [row, col] in the next block

lib/runtime/evaluation.coffee, lib/runtime/frontend.coffee
which required for this to work with newer electron versions (I think; will have to test more)
cc @ashnur, maybe you can try this branch sometime on Arch
=> require remote from electron

lib/connection/local.coffee, lib/connection/process/basic.coffee, lib/connection/process/tcp.coffee, script/boot.jl
part of https://github.com/JunoLab/Atom.jl/pull/63
note: must make sure julia-0.4 branch supports this before releasing.
=> Use julia-as-client by default

lib/runtime/evaluation.coffee
=> goto panel

lib/misc.coffee, lib/ui.coffee, lib/ui/progress.coffee
=> Progress refactoring take 2

lib/runtime/console.coffee
=> clear-console preserves current input

lib/ui.coffee, lib/ui/progress.coffee
Updates for https://github.com/JunoLab/atom-ink/pull/95.
=> update ink progress api

CHANGELOG.md, lib/package/config.coffee, lib/runtime/evaluation.coffee
This really *really* needs to be refactored, but in the meantime I've made it even more horrible. :)
Fixes https://github.com/JunoLab/atom-julia-client/issues/59 and https://github.com/JunoLab/atom-julia-client/issues/325.
=> option for displaying editor results in console

lib/runtime/frontend.coffee, lib/ui/notifications.coffee
implements https://github.com/JunoLab/Juno.jl/issues/52.
Needs https://github.com/JunoLab/Atom.jl/pull/83 and https://github.com/JunoLab/Juno.jl/pull/54 to work.
https://github.com/JunoLab/JunoDocs.jl/pull/19 for docs
=> notification api

lib/runtime/evaluation.coffee
https://github.com/JunoLab/atom-ink/pull/127
=> follow new ink api

lib/connection/client.coffee, lib/package/config.coffee
Depends on https://github.com/JunoLab/Atom.jl/pull/85
=> Arguments setting

lib/ui/highlighter.coffee, lib/ui/views.coffee
https://github.com/atom/highlights/commit/5a971ac4cfb53a55a0d24dc21e2182d84ed079f4
This got broken by Atom's shadow-dom changes.
=> Fix syntax highlighting

lib/julia-client.coffee, lib/runtime.coffee, lib/runtime/profiler.js, lib/ui/views.coffee
All the complicated stuff was done by @MikeInnes, I just rebased and made some few improvements.
Depends on https://github.com/JunoLab/atom-ink/pull/133 and https://github.com/JunoLab/Juno.jl/pull/60.
=> In-editor Profile Viewer

lib/connection/process/basic.coffee, lib/package/config.coffee
Fixes https://github.com/JunoLab/Juno.jl/issues/61
@ChrisRackauckas: Would you mind trying this real quick on Windows? I'd have to reboot to try if this works there ;)
=> add option for multiple threads

lib/misc.coffee, lib/misc/weave.js, lib/package/commands.coffee, lib/runtime/evaluation.coffee
supercedes https://github.com/JunoLab/atom-julia-client/pull/318.
=> Weave: run-weave-chunks

lib/julia-client.coffee, lib/misc/words.coffee, lib/runtime.coffee, lib/runtime/evaluation.coffee, package.json
Requires [nuclide/hyperclick](https://atom.io/packages/hyperclick) (but nothing breaks without).
Prompted by https://github.com/JunoLab/atom-julia-client/issues/76#issuecomment-311043474 (cc @kindlychung).
TODO:
=> Hyperclick

lib/runtime/plots.coffee, lib/runtime/profiler.js
requires https://github.com/JunoLab/atom-ink/pull/139
=> Make plotpane pannable and zoomable

lib/misc.coffee, lib/misc/colors.js, lib/runtime/frontend.coffee, styles/julia-client.less
allows julia to query a select few syntax colors.
=> get syntax colors

lib/package/commands.coffee
Thanks for the guide @pfitzseb !
=> update path to startup file

lib/runtime/plots.coffee
Requires https://github.com/JunoLab/atom-ink/pull/174.
With those PRs you can call e.g. `
```julia
Atom.msg("newpane", "id", "data:text/html,<div>Hi there</div>", Dict(:icon => "graph", :title => "Foo", :split => "right"))
```
and that will open a new pane (if there's none open with that `id`).
=> basic HTML pane implementation

lib/misc/cells.js, lib/misc/weave.js
Fixes https://github.com/JunoLab/Juno.jl/issues/224.
=> improve weave integration

lib/connection.coffee, lib/connection/local.coffee
Fixes https://github.com/JunoLab/Juno.jl/issues/249.
=> allow starting remote session without local julia install

lib/package/config.coffee, lib/runtime/console2.js
Fixes https://github.com/JunoLab/Juno.jl/issues/248 (by removing the link validation -- this leads to more false positive, but tbh, who cares) and https://github.com/JunoLab/atom-julia-client/issues/552.
=> drastically improve link handling

lib/misc/weave.js
Addresses https://github.com/JunoLab/Juno.jl/issues/325
=> Fixed line numbers for weave cell evaluation.

lib/package/config.coffee
https://discourse.julialang.org/t/ann-juno-0-8-8/26214/8?u=aviatesk
=> Change the description of `Open Default Panes on Startup`

lib/package/config.coffee, lib/runtime/console2.js, lib/runtime/evaluation.coffee, lib/runtime/frontend.coffee, lib/ui/docs.js, lib/ui/layout.js, lib/ui/views.coffee
Introduces `Open files in pending state` config.
Please refer to the description of the config for why I want to introduce this: 
https://github.com/JunoLab/atom-julia-client/pull/579/files#diff-5655a196ecf76f9731b64509e8b7676aR141-147
The corresponding PR on atom-ink is: https://github.com/JunoLab/atom-ink/pull/208
=> Pending open

lib/package/config.coffee, lib/ui/notifications.coffee
to work around Atom crash on MacOS
=> disable OS notifications

lib/connection/client.coffee, lib/connection/messages.coffee, lib/package/commands.coffee, lib/package/config.coffee, lib/package/menu.coffee, lib/runtime.coffee, lib/runtime/completions.js, lib/runtime/console2.js, lib/runtime/workspace.coffee, lib/ui/layout.js
refer to https://github.com/JunoLab/Atom.jl/pull/153 for details
refactors included
- allow preceding whitespaces in function calls: closes #588 (dup)
- ~~remove PlatformIO integration~~
- update menus / better messages using Markdown strings
=> consistent types

lib/package/commands.coffee, lib/ui/layout.js
Fixes https://github.com/JunoLab/Juno.jl/issues/345.
=> close-juno-panes command

lib/julia-client.coffee, lib/runtime.coffee, lib/runtime/completions.js, lib/runtime/urihandler.js, lib/ui/docs.js, package.json
xref: https://github.com/JunoLab/Atom.jl/pull/164
=> add uri-handler for completions

lib/runtime/completions.js
ref https://github.com/JunoLab/Atom.jl/pull/165
=> local completions

lib/julia-client.coffee, package.json
and automatically load all deps. Also show better notifications.
=> require language-julia

lib/runtime/datatip.js
ref: https://github.com/JunoLab/Atom.jl/pull/173
=> show value information during debugging

lib/julia-client.coffee, lib/runtime/frontend.coffee, script/boot_repl.jl
and show a warning if it's too old.
=> check atom version on boot

lib/julia-client.coffee, lib/misc/words.js, lib/runtime/datatip.js, lib/runtime/goto.js
This feature won't fit well into the naming `julia-client: goto-symbol`, but I implemented this under the command as well anyway.
=> file jumps

lib/misc/blocks.js
Fixes https://github.com/JunoLab/Juno.jl/issues/367, and makes it possible to evaluate docstrings by selecting them.
=> fix string block finding

lib/package/commands.coffee, lib/runtime/evaluation.coffee, menus/julia-client.cson
Fixes https://github.com/JunoLab/Juno.jl/issues/383.
=> work in folder in tree view

lib/misc/blocks.js, lib/misc/scopes.js, lib/runtime/datatip.js, lib/runtime/goto.js, lib/runtime/outline.js, lib/runtime/workspace.coffee, lib/ui/docs.js
ref: https://github.com/JunoLab/Atom.jl/pull/192
=> enhanced symbols

keymaps/julia-client.cson.cmd, keymaps/julia-client.cson.ctrl, lib/connection/messages.coffee, lib/package/commands.coffee, lib/package/config.coffee, lib/package/menu.coffee, lib/package/toolbar.coffee, lib/runtime/console.js
Terminal, REPL, and External Terminal should be fairly consistent now.
Motivated by https://github.com/JunoLab/atom-julia-client/pull/613#issuecomment-531374915.
=> more consistent lingo

lib/connection/process/remote.js, script/boot_repl.jl
Shell escaping is fun. Or something.
But at least this works.
=> fix remote exec escaping

script/boot_repl.jl
=> shorten boot_repl script

lib/runtime/outline.js
fixes https://github.com/JunoLab/Juno.jl/issues/407
ref: https://github.com/JunoLab/Atom.jl/pull/205
=> don't update symbols on editor switching

lib/package/commands.coffee, lib/runtime/evaluation.coffee, menus/julia-client.cson
as a command and in the tree-view context menu.
Fixes https://github.com/JunoLab/Juno.jl/issues/206.
=> activate environment support

lib/package/menu.coffee
For https://github.com/JunoLab/atom-julia-client/issues/649
=> menu: current file's folder menu item fix

script/boot_repl.jl
part of the fix for https://github.com/JunoLab/Juno.jl/issues/450.
=> access Base.ARGS directly

lib/connection/process/cycler.coffee, lib/runtime/completions.js
- use `blocks.getLocalContext` instead of `blocks.get`
- a bit rename refactor
- rm cacheCompletions
=> refactor completions.js:

lib/package/commands.coffee, lib/package/menu.coffee, lib/runtime/evaluation.coffee, menus/julia-client.cson
needs https://github.com/JunoLab/Atom.jl/pull/241
=> `activate`environment-in-parent-folder` command

lib/misc/cells.js, lib/ui.coffee, lib/ui/cellhighlighter.js, styles/julia-client.less
Fixes https://github.com/JunoLab/Juno.jl/issues/449.
=> highlight current cell

lib/misc/blocks.js, lib/misc/cells.js, lib/package/config.coffee, lib/ui.coffee, lib/ui/cellhighlighter.js
and make cell highlighting optional
=> improve cell detection logic

lib/connection/local.coffee
Fixes https://github.com/JunoLab/Juno.jl/issues/453.
=> kill proc on end/error

lib/misc/blocks.js
Fixes https://github.com/JunoLab/Atom.jl/issues/237
=> return 0 if there is no local context

lib/package/config.coffee, lib/runtime.coffee, lib/runtime/formatter.js
Fixes https://github.com/JunoLab/Juno.jl/issues/363.
=> add option for format-on-save

lib/package/config.coffee, lib/runtime/console.js
Requires https://github.com/JunoLab/atom-ink/pull/251.
=> option for ctrl/cmd modifier when clicking link

lib/ui/docs.js
xref: https://github.com/JunoLab/Atom.jl/pull/232
=> erase module input when it's been changed in backend

lib/misc/paths.coffee, lib/package/commands.coffee, lib/package/menu.coffee, lib/runtime/debugger.js, lib/runtime/evaluation.coffee, menus/julia-client.cson
Of course I made this module-aware.
=> run/debug files from tree-view context

lib/misc/blocks.js
Fixes https://discourse.julialang.org/t/strange-behavior-in-live-line-evaluation/32497 and makes a few general improvements.
=> improve block finding algorithm yet again

lib/runtime/evaluation.coffee
Fixes https://github.com/JunoLab/Juno.jl/issues/486.
=> make sure cell eval can display in console

lib/runtime/modules.coffee, script/boot_repl.jl
Requires https://github.com/JunoLab/Atom.jl/pull/288.
=> improve repl module detection speed

lib/runtime/debugger.js, styles/julia-client.less
Thanks to @jkrumbiegel for designing those icons!
Requires https://github.com/JunoLab/atom-ink/pull/262.
=> better debugger buttons

lib/connection.coffee, lib/connection/client.coffee, lib/connection/local.coffee, lib/connection/process/basic.js, lib/connection/process/remote.js, lib/runtime/completions.js, lib/runtime/console.js, lib/runtime/debugger.js, lib/runtime/evaluation.coffee, lib/runtime/formatter.js, lib/runtime/goto.js, lib/runtime/modules.coffee, lib/runtime/outline.js, lib/runtime/urihandler.js
=> Fix Atom crashes on Windows

lib/package/config.coffee, lib/ui/cellhighlighter.js, styles/julia-client.less
=> more subtle cell highlighting

lib/julia-client.coffee, lib/runtime/console.js, styles/julia-client.less
Requires https://github.com/JunoLab/atom-ink/pull/267.
=> terminal tooltips

lib/package/config.coffee, lib/runtime.coffee, lib/runtime/completions.js
configurable ! needs https://github.com/JunoLab/Atom.jl/pull/308
=> fuzzy completion mode

lib/package/config.coffee
Fixes https://github.com/JunoLab/Juno.jl/issues/551.
=> default to -O2

lib/runtime/modules.coffee, lib/ui/selector.js, styles/julia-client.less
- fix error on module selection
- fix styling
- fix errors on item filtering when items are Object
=> follow #722:

lib/package/config.coffee, lib/runtime/formatter.js
corresponds to: https://github.com/domluna/JuliaFormatter.jl/pull/221
=> support .JuliaFormatter.toml config file

lib/ui.coffee, lib/ui/progress.coffee
requires https://github.com/JunoLab/atom-ink/pull/272
=> hide progress bar on client detached

lib/connection/process/basic.js, lib/connection/process/remote.js, lib/package/config.coffee
=> pkg server setting

lib/runtime/formatter.js
Fixes https://github.com/JunoLab/Juno.jl/issues/567.
=> restore cursor pos when formating

lib/connection/client.coffee, lib/package/commands.coffee, lib/package/menu.coffee, lib/runtime.coffee, lib/runtime/console.js, lib/runtime/environments.js, lib/runtime/modules.coffee, lib/runtime/workspace.coffee, lib/ui/selector.js, menus/julia-client.cson
requires https://github.com/JunoLab/Atom.jl/pull/330
=> project monitor tile
