lib/connection/terminal.coffee
lib/julia-client.coffee

This is a Linux-only config at the moment (I'd like it to be more general), wasn't sure how to set different defaults for each platform. I've set ``xterm`` as the default since I guessed it's probably installed in more places, happy to change it back to ``x-terminal-emulator`` though if that's the default you want.
Relatedly, have you though of leveraging [term](https://github.com/tjmehta/atom-term) or the [term2](https://github.com/webBoxio/atom-term2) fork instead of opening an external one? They seem to handle the Julia REPL fairly well.

Add config for custom terminal.

---

docs/README.md

Atom was complaining that ink and julia-client couldn't find atom-space-pen-views.
Devs need to run `apm install` from repo dir to have node grab it

DOC: note about apm install to get space-pen-views to build

---

lib/modules.coffee

This PR adds debouncing to cursor moves, so we don't try to update
the module we're evaluating into until the user stops moving the
cursor. I was noticing pretty high CPU usage and laggy performance
when typing or moving the cursor with the keyboard.
It also does some refactoring to modules.coffee. The `update` method
was being used to handle a bunch of different callbacks that did
different things depending on the state. This splits out into a
couple different callback handlers. `update` is now only for actually
sending the message to the julia process.

Debounce module updates on cursor move

---

lib/connection/process.coffee
lib/julia-client.coffee

causing `process.platform` to be undefined.
This leads to e.g. the default platform setting to be wrong on Windows.
ref #35

fix for `process` being shadowed by imports

---

keymaps/julia-client.cson

We were just using .conosle and that doesn't work anymore

Keybindings for console require .ink-console css selector

---

lib/connection/process.coffee

This will prevent any custom PowerShell startup scripts a user might have from running.
In my case I have code in my startup script that doesn't work when called from Atom, just generating errors that are seen in the julia console in Atom. This PR fixes that.

Add NoProfile option to PowerShell call

---

lib/connection/terminal.coffee

`sh` would be escaped so something like `"\"julia\""`, which doesn't work. 
Dunno if this works on linux, someone might wanna check that ;)

fix escaping bug on windows when opening REPL

---

keymaps/julia-client.cson
lib/eval.coffee
lib/julia-client.coffee

So I basically cleaned up and restructured what code I had for getting methods and documentation on a function or macro.
Atom.jl-side: https://github.com/JunoLab/Atom.jl/pull/17
atom-ink-side: https://github.com/JunoLab/atom-ink/pull/21
This design should be kinda okayish -- let me know what you think ;)
Also: We need default keybindings for those, I think. `Ctrl+D` and `Ctrl+M` are taken, so we could of course do something like `Ctrl+J Ctrl+D/M`. Suggestions?

Add commands for getting docs/methods

---

manual/README.md

The latest master of JuliaParser is now tagged, so the checkout should no longer be necessary.

Remove JuliaParser instructions from README

---

lib/config.coffee
lib/connection/process.coffee
lib/julia-client.coffee

Split into own file for organisational purposes, and adds options depending on the system so that we don't have any "only works on windows" options.

Rejigger the config

---

lib/config.coffee
lib/connection/process.coffee
lib/connection/spawnInterruptibleJulia.ps1

and a couple of windows fixes in process.coffee.
@one-more-minute: The additional `cwd: @workingDir()` you added to the `powershell` invocation errors for me -- powershell cannot be spawned with it there.
I also added the early return in `checkExe` you suggested.

Modified ps script for working interrupts on Windows

---

lib/runtime/modules.coffee

Before this change:
After the change:

maintain spacing in status bar module indicator

---

lib/connection/process.coffee

and spawn julia in the first open project folder (or its parent if that is a file), as per [here](https://github.com/JunoLab/atom-julia-client/issues/124#issuecomment-193303789).

make checking the julia executable more robust

---

lib/connection.coffee
lib/package/config.coffee

This adds an option to have Julia runtime errors show up in the console rather than using Atom's notification UI when evaluating from the source file. 
It isn't finished as I didn't have a chance to hook up the part where we send the error to the console. I don't have time to dig into it myself right now, so if either @MikeInnes @pfitzseb  could fill in the `TODO` I logged to the console that would be great.
Thanks!
cc @simonbyrne

WIP: option to bypass atom's notification UI for errors

---

lib/connection.coffee
lib/connection/client.coffee
lib/connection/process.coffee
lib/connection/tcp.coffee
lib/julia-client.coffee
lib/package/commands.coffee
lib/runtime/console.coffee
lib/runtime/modules.coffee
package.json

Cleans up the connection architecture and exposes the `client` object as a service.
What this means is that if packages want to extend what Juno can do – including by adding new ways of connecting to a client, e.g. over SSH – they can just grab the `client` object and get on with it. Equally, it might be possible to e.g. implement a profiler as an Atom plugin + Julia package on top of Atom.jl and julia-client.
Couple extras: better error messages, and a command which sends text to Julia's STDIN.

Julia As A Service

---

lib/connection/client.coffee
lib/package/config.coffee

motivated by #151.
Also change the recently introduced `Errors To Console` option to an opt-out setting for notifications for those kinds of errors.
julia side: https://github.com/JunoLab/Atom.jl/pull/34
cc: @dlfivefifty

internal errors always rendered in console, notification is opt-out

---

lib/package/config.coffee
lib/runtime/console.coffee

Fixes #166, requires https://github.com/JunoLab/atom-ink/pull/51.
Not sure how sensible that default is though...

limit the console history's size

---

lib/connection/process.coffee
lib/misc/paths.coffee

This fixes #159. 
Only works with a functioning and correctly set julia executable, but I think that's a tradeoff everyone should be okay with. 
The regexp for getting the current version may or may not be a good idea -- no clue if Julias versioning scheme will change anytime soon. Maybe I should add a generic fallback similar to what we had before, but not sure. Opinions?

get the correct versions packages

---

lib/julia-client.coffee
package.json

We could probably get rid of all those `withInk`s, but then again ink might be activated while Juno runs...

install Ink via atom-package-deps

---

lib/ui/highlighter.coffee
lib/ui/views.coffee
package.json

This seems like it may be general enough to have it in Ink, not sure though. 
I'd really like to get rid of the Highlights dependency soon, because it's necessary to patch master on Windows to get it running.

Highlighting in results without external dependency

---

lib/connection/client.coffee
lib/package/commands.coffee

This warning served a debugging purpose at one point but I don't think it's necessary now, given that killing is idempotent anyway. It's like having a warning "this file has already been saved".
I also added an ipc reset on kill if there's no active client. Strictly speaking, having work without a client is a state we should avoid getting into, but this is a better behaviour if we do reach that state.

Don't warn on `kill` if there's no client

---

lib/connection/client.coffee
lib/connection/messages.coffee
lib/connection/process/tcp.coffee
lib/connection/terminal.coffee
lib/package/commands.coffee

This adds a simple (but much nicer than before) UI for connecting from an external Julia process, e.g. in the terminal or IJulia.

Connect to external processes

---

lib/package/config.coffee
lib/runtime/evaluation.coffee

Adds option in the settings menu to change whether results are displayed inline (current behavior) or underneath using the `type` option in `ink.Results`. See https://github.com/JunoLab/atom-ink/pull/93

Adds option to display results as blocks

---

lib/julia-client.coffee
lib/package/commands.coffee
lib/package/config.coffee
lib/ui.coffee
lib/ui/layout.js

The idea of this is to have commands which put Juno into an ide-esque layout without a lot of manually moving things around. There's also an option to do this by default on startup – we could enable this by default in uber-juno, but I haven't for now as I'm concerned it'll be too annoying for many users.

Layout logic

---

lib/package/commands.coffee
lib/runtime/completions.coffee
lib/runtime/debugger.js
lib/ui/views.coffee
styles/julia-client.less

While this implementation basically works, there's still a lot to figure out:
Just for reference (need to get those if you want to try this branch):
- https://github.com/JunoLab/Atom.jl/tree/sp/breakpoints
- https://github.com/JunoLab/atom-ink/tree/sp/breakpoints

WIP: Breakpoint UI

---

CONTRIBUTING.md
lib/connection/messages.coffee

Shuld Juno always use "usage" category in Juila forum? or Juno can use "Development" category as well.

Update Juno forum address to 'discourse.julialang.org'

---

lib/julia-client.coffee
lib/ui/layout.js

Currently the "use standard layout" option never activates. This fixes that by ignoring the three docks.
Eventually we'll want to use docks for our layout anyway, but this gives us a short term fix.

Layout fix for 1.17

---

lib/connection/process/basic.coffee
lib/package/config.coffee
package.json

by default. Have to use `physical-cpu-count` instead of `require('os').cpus().length` to account for hyperthreading.
cc @chrisrackauckas

Set number of threads to number of cores

---

keymaps/julia-client.cson
lib/connection/client.coffee
lib/connection/process/basic2.js
lib/runtime/console2.js
package-lock.json

fixes #403.
This has the added benefit that you can use one keybinding everywhere and it will do the smart thing and interrupt either in-editor or in the repl, depending on which is currently running something.
@MikeInnes: I'm not sure if this works for macs, so would be great if you could check.

unify copy and interrupt keybindings

---

lib/connection/client.coffee
script/boot_repl.jl
script/boot_sync.jl

This makes sure that `pwd()` is correct as well as that communication works.
Mainly motivated by the fact that I want to generate an OhMyREPL theme, but for that to work together with the process cycler we need to defer any Atom <-> Julia communication until there's a connection.
Putting 
```
using OhMyREPL, Crayons
using OhMyREPL: Passes.SyntaxHighlighter
function generateOMRtheme()
cs = SyntaxHighlighter.ColorScheme()
colors = Juno.syntaxcolors()
SyntaxHighlighter.symbol!(cs, Crayon(foreground = colors["symbol"]))
SyntaxHighlighter.comment!(cs, Crayon(foreground = colors["comment"]))
SyntaxHighlighter.string!(cs, Crayon(foreground = colors["string"]))
SyntaxHighlighter.call!(cs, Crayon(foreground = colors["funccall"]))
SyntaxHighlighter.op!(cs, Crayon(foreground = colors["operator"])) …
```

only load .junorc.jl after connection established

---

lib/package/commands.coffee

`connnect` -> `connect`
Also getting practice at pull requests, I guess I could have just mentioned this on Slack >.>

Fixed Typo in Atom Command

---

README.md

The maintained installation instructions seems to be at http://docs.junolab.org/latest/man/installation.html or https://github.com/JunoLab/JunoDocs.jl/blob/master/docs/src/man/installation.md, but not at https://github.com/JunoLab/uber-juno/blob/master/setup.md.

Change link to installation instructions in the docs

---

lib/connection/process/tcp.coffee
lib/package/config.coffee

Per [this thread](https://discourse.julialang.org/t/connecting-juno-to-work-with-julia-installed-on-a-remote-server/7494/14), it would be nice to have the option to use a static port for use with persistent ssh connections. This pull request implements this feature.

Optionally allow for static port in "Connect External Process"

---

lib/misc/cells.js

On Linux & OSX (at least), the line number offsets in the returned stack track attributed the error to the wrong line. This is because for block-evaluations line = end, rather than line = start (which is what it was for single-line evals). Usine line=start+1 fixes this in all my tests so far. 
Steps to test and reproduce.
Open Atom with uber-juno installed.
Make sure the file has the Julia language selected. 
Enter the following example
~~~~
function myfun()
x = 1+b
return x
end
myfun()
~~~~
Run this as a cell with Alt-Enter.
Expected result: the line x=1+b is highlighted.
Produced result: no line is highlighted and the error is indicated on line 6.
Result with patch: the correct line is highlighted.

Correct line number offset in error messages

---

lib/package/toolbar.coffee

It seems like font awesome has updated the name of "Floppy Icon" from `floppy-o` to `save`. And that caused the icon to disappear from the toolbar. Here is a fix for that.

toolbar: save icon name updated to sync with fa's update

---

menus/julia-client.cson

Fixed some typos in the julia-client.cson file. Issue here: https://github.com/JunoLab/Juno.jl/issues/189#issue-381835022

Changed 'Defintion' to 'Definition' and 'Run block' to 'Run Block'

---

lib/connection.coffee
lib/connection/client.coffee
lib/connection/local.coffee
lib/connection/messages.coffee
lib/connection/process/basic2.js
lib/connection/process/remote.js
lib/connection/process/tcp.coffee
lib/julia-client.coffee
lib/package/commands.coffee
lib/package/config.coffee
lib/package/toolbar.coffee
lib/runtime/console2.js
lib/runtime/evaluation.coffee
lib/runtime/modules.coffee
package.json
script/boot_repl.jl

Still lots to do...
Also needs https://github.com/JunoLab/atom-ink/pull/184 and https://github.com/h3imdall/ftp-remote-edit/pull/228.

Native remote connection support

---

lib/ui/focusutils.js

The commit [add `return-from-goto` command](https://github.com/JunoLab/atom-julia-client/commit/6223ca68efd8fc1832d4321844858808b97eaa3a) removes the functionality for `julia-client:focus-last-editor` and `julia-client:focus-last-terminal`.
I'm not sure this is an intentional change, but I believe this functionality should be so much useful for some users that I recovered it.
I also refactored the file a bit with following changes:
- Add identifiers to variables (suggested by eslint)
- Removed unused functions (grep-based check for usages in the whole project)
- Use Atom `CompositeDisposable` for disposer

Recover `focus-last-editor/terminal` functionality

---

lib/package/commands.coffee
lib/package/menu.coffee
lib/runtime/debugger.js
menus/julia-client.cson

This PR enables an user to easily create a conditional breakpoint.
Behaviour of `toggle-conditional-breakpoint`:
- If there is no breakpoint: Create a brand new conditional breakpoint
- If there is already a non-conditional/conditional breakpoint: Edit its condition
The corresponding PR in atom-ink: https://github.com/JunoLab/atom-ink/pull/204

Add a command to toggle conditional breakpoint

---

lib/connection/process/basic.coffee
lib/connection/process/basic2.js
lib/julia-client.coffee
lib/package/commands.coffee
lib/package/config.coffee
lib/package/settings.js
lib/runtime/completions.coffee
lib/runtime/console2.js
lib/runtime/debugger.js
lib/runtime/evaluation.coffee
lib/runtime/linter.js
lib/runtime/plots.coffee
lib/runtime/profiler.js
lib/runtime/workspace.coffee
lib/ui.coffee
lib/ui/docs.js
lib/ui/layout.js

Even though Juno's serialization works well, we still have to manually layout various panes at the beginning of the project or the later.
This PR addresses this by adding custom layout options so that users can set up their own default layout, i.e.: the default location and the splitting direction of any Juno pane.
The possible drawback will be that these settings can be messed up. Thus I took the two approaches below:
1. Set the default settings to such values that they behave _exactly_ the same way as before
2. Made these settings collapsed by default so that users won't feel bother at them. Only users who want to tweak the default pane-opening settings, they can as they want.
Furthermore, I use [this new enum config settings](https://github.com/atom/settings-view/pull/1089) and I think …

Feature - Add custom layout options

---

keymaps/julia-client.cson
lib/package/commands.coffee
lib/package/config.coffee
lib/package/menu.coffee
lib/package/toolbar.coffee
lib/runtime/evaluation.coffee
spec/eval.coffee
spec/juno-spec.coffee

- Make config for setting scopes that Julia-Client would recognise as Julia file:
* Default to `['source.julia', 'source.weave.md', 'source.weave.latex']`
- Disable `provideHyperclick` for non-Julia files
- Register `atom-text-editor` specific commands only for Julia `atom-text^editor`s
* Can speed up package loading time for non-Julia projects: but atst can cause unexpected states around serialization: Once atom-ink is merged into julia-client, this would need more tweaks that moving serialization into package.json.

Make Julia-Client more grammar-sensible

---

keymaps/julia-client.cson
lib/connection/client.coffee
lib/package/commands.coffee
lib/package/menu.coffee
lib/package/toolbar.coffee
lib/runtime.coffee
lib/runtime/formatter.js
lib/ui/layout.js
menus/julia-client.cson

This PR adds `Julia-Client: Format-Code` command to format code in a currently opened editor.
The corresponding PR on Atom.jl side is: https://github.com/JunoLab/Atom.jl/pull/142
This PR also clean up command/keymap registries. This is basically done in [this commit](https://github.com/JunoLab/atom-julia-client/commit/b1c5cf24db371d5521a9156b59941662f2641e05) so please refer to the commit message and the changes

Create command to format code in a current editor

---

.travis.yml

Enables Travis build for `Atom>=1.39.0` by using Xenial image.
The build on OSX still keeps failing though, and I've not found the package example which succeeds to build the current
Atom version on OSX.
https://github.com/atom/wrap-guide/blob/master/.travis.yml

Fix build of Atom-beta in Travis CI

---

lib/runtime/console2.js

Fixes https://github.com/JunoLab/Juno.jl/issues/340.

fix Meta-Enter

---

styles/julia-client.less

it's better to keep it minimum where the global style override occurs.

migrate autocomplete stlye from ink

---

lib/misc/blocks.js

Fixes https://github.com/JunoLab/Juno.jl/issues/357 and simplifies the code a bit.
Not sure if I like relying on language-julia, but we basically control that too, so should be fine. #610 should make sure that everyone has that package installed.

ignore toplevel strings when finding code blocks

---

lib/runtime/completions.js

Works pretty well for me -- snippets are still there (they have `inclusionPriority: 1`), as are latex-completions (with `inclusionPriority: 5`).
The one thing we need to think about is removing the `disableForSelector = '.source.julia .comment'` line, because that means you still end up with the default completions in comments. Thoughts?

exclude default completion provider

---

lib/package/toolbar.coffee

Some icons have gone missing following the most recent update to the toolbar package because the ion icons now need the `md-` prefix; also, `stop` is now called `square`.
see, e.g.
https://github.com/suda/tool-bar/releases/tag/v1.2.0
https://github.com/suda/tool-bar/issues/264

Update toolbar for missing icons

---

lib/package/config.coffee
lib/runtime/evaluation.coffee

Needs https://github.com/JunoLab/Atom.jl/pull/195 to actually do something.
Fixes https://github.com/JunoLab/Juno.jl/issues/378 and https://github.com/JunoLab/Juno.jl/issues/381.

add an option to always show errors in REPL when using inline evaluation

---

lib/ui/focusutils.js

Then we can invoke `focus-last-editor` and `focus-last-terminal` commands from the very beginning.

initialize `lastEditor` and `lastTerminal` after package activation

---

lib/package/commands.coffee
lib/package/menu.coffee
lib/runtime/console.js
menus/julia-client.cson

I often want this when editing files outside of a current project.
Or maybe creating commands like `julia-client: new-(remote-)terminal-from-active-directory` (which will just start a terminal within a currently active editor's directory) is more preferable ?

open terminal from a text editor's directory

---

lib/runtime/goto.js
lib/runtime/outline.js

Helps https://github.com/JunoLab/Atom.jl/pull/215:
- add goto supports for unsaved editors
- add `clear-symbols-cache` command
***
Requires https://github.com/JunoLab/Atom.jl/pull/215.

misc updates around https://github.com/JunoLab/Atom.jl/pull/215

---

lib/runtime/evaluation.coffee

for keyboard shortcut people like me :)
***
Now those behaviours are a bit implicit -- maybe separating those tree-view-related behaviours into new commands like `work-in-active-folder-in-tree-view` and `activate-environment-in-active-folder-in-tree-view` and register them `.tree-view` selector would be more explicit.

work in folder and activate project commands with focusing on tree-view

---

lib/ui.coffee
lib/ui/cellhighlighter.js

When we switch editors quickly, currently we have small errors around cell highlighting:
```
Uncaught (in promise) TypeError: Cannot read property 'destroy' of null
at file:///C:/Users/aviat/github/atom-pkgs/atom-julia-client/lib/ui/cellhighlighter.js:36:24
at wrapped (C:\Users\aviat\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:1213931)
at Function.simpleDispatch (C:\Users\aviat\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:1212922)
at Emitter.emit (C:\Users\aviat\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:1214363)
at TextEditor.destroy (C:\Users\aviat\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:7180)
at Pane.destroyItem (C:\Users\aviat\AppData\Local\atom\app-1.43.0\resources\app\static\<embedded>:11:461289) …
```

fix subtle errors in cell highlighting

---

lib/package/config.coffee
lib/runtime/formatter.js

Will work with: https://github.com/JunoLab/Atom.jl/pull/259

allow formatting options

---

keymaps/julia-client.cson.cmd
keymaps/julia-client.cson.ctrl
lib/julia-client.coffee
lib/misc/paths.coffee
lib/package/commands.coffee
lib/package/menu.coffee
lib/runtime/console.js
lib/runtime/debugger.js
lib/runtime/evaluation.coffee
menus/julia-client.cson
script/boot_repl.jl

Requires https://github.com/JunoLab/Atom.jl/pull/269.
Requires https://github.com/JunoLab/atom-ink/pull/255.
Requires https://github.com/JunoLab/atom-ink/pull/256.

debug file

---

lib/misc/blocks.js

Fixes both multiline backtick strings and modules:
````
```
kjgkg
```
module Foo
1+1
2+2
3+3
end
````
Regression tests would probably help a lot here, but  ¯\\\_(ツ)\_/¯

fix block finding

---

lib/runtime/plots.js

Fixes https://github.com/JunoLab/Juno.jl/issues/488.
Still problematic for really big objects because the `show` method will take a looong time.

use object URLs instead of data urls to support objects > 2mb

---

lib/connection/client.coffee
lib/connection/local.coffee
lib/connection/process/cycler.coffee
package-lock.json
package.json
script/boot_repl.jl

- fix cycler caching with empty args
- invalidate cache when julia options change
- move versionwarning call into juliarc handler
Fixes https://github.com/JunoLab/Juno.jl/issues/454.
Fixes https://github.com/JunoLab/Juno.jl/issues/491.

cycler improvements

---

lib/connection/messages.coffee
lib/connection/process/basic.js
lib/misc/paths.coffee

Turns out that Windows' `where` can't deal with full paths, so this introduces a special case for absolute paths on windows.

fix path error messages on windows

---

lib/runtime/outline.js

- use `onDidStopChangingActivePaneItem` API instead of 
`onDidChangeActiveTextEditor` for more throttled works
- handle grammar change correctly (non-julia to julia pass)
- handle initially opened editor correctly
- more disposing (while keeping them safe)

improve outline subscriptions

---

lib/package/config.coffee

Some style guides (such as [YASGuide](https://github.com/jrevels/YASGuide)) recommend using the following section headers:
```
#####
#####
```
This conflicts with the default cell delimiters regexps of Juno, which would create three cells when seeing the header above.
**Proposed fix:** replace the `##` regexp by `##\s`, as suggested by @pfitzseb on Slack.
Signed-off-by: Jonathan Laurent <jonathan.laurent@cs.cmu.edu>

Better default for cell delimiters

---

lib/runtime/goto.js
lib/runtime/workspace.coffee
lib/ui/docs.js

So we don't need `ink.goto` anymore.
Corresponds to https://github.com/JunoLab/atom-ink/pull/271

just use julia-client's selector

---

lib/package/config.coffee

So that https://unix.stackexchange.com/questions/12107/how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal can't accidentally happen.

Add Ctrl-S to whitelisted REPL keybindings
